apiVersion: v1
kind: Service
metadata:
  name: pipeline-app-service
  namespace: savitest
spec:
  selector:
    app: pipeline-app
  ports:
    - protocol: TCP
      port: 8000       # Internal Pod Port
      targetPort: 8000 # Container Port
      nodePort: 30080  # Exposed Port (Choose between 30000-32767)
  type: NodePort

