apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-app
  namespace: savitest   #Present in RHEL CLUSTER
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipeline-app
  template:
    metadata:
      labels:
        app: pipeline-app
    spec:
      containers:
      - name: fastapi-app
        image: savinpandey/pipeline:v13
        ports:
        - containerPort: 8000
        env:
        - name: APPNAME
          value: "Yantras"
